version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
      - nvm install 18
      - nvm use 18
      - npm install -g typescript
      - npm install
      - npm install @types/node
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
cache:
  paths:
    - 'node_modules/**/*'
artifacts:
  exclude-paths: 
    - node_modules/**/*
  files:
    - '**/*'
  name: chatApp-$(date +%Y-%m-%d)